In [15]:
!pip install torch

In [16]:
import torch 
import torch.nn as nn

In [17]:
#input
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [18]:

neuron=nn.Linear(in_features=3,out_features=1)

In [19]:
output=neuron(inputs)

In [20]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [21]:
#verify the formula
neuron.weight  @ inputs +neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [22]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)

In [23]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)